
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 分支规则
/// </summary>
public sealed partial class BranchRule : Luban.BeanBase
{
    public BranchRule() { }
    
    public BranchRule(ByteBuf _buf) 
    {
        Reply = _buf.ReadString();
        MinAffection = _buf.ReadInt();
        MaxAffection = _buf.ReadInt();
        NextNode = _buf.ReadString();
    }

    public static BranchRule DeserializeBranchRule(ByteBuf _buf)
    {
        return new BranchRule(_buf);
    }

    public string Reply;
    public int MinAffection;
    public int MaxAffection;
    public string NextNode;

    public const int __ID__ = -948409378;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref BranchRule other)
    {
        if (other == null)
        {
            other = new BranchRule();
        }
        other.Reply = Reply;
        other.MinAffection = MinAffection;
        other.MaxAffection = MaxAffection;
        other.NextNode = NextNode;
    }

    public BranchRule DeepCopy()
    {
        var other = new BranchRule();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "reply:" + Reply + ","
        + "minAffection:" + MinAffection + ","
        + "maxAffection:" + MaxAffection + ","
        + "nextNode:" + NextNode + ","
        + "}";
    }
}
}

