
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 情绪好感规则
/// </summary>
public sealed partial class EmotionAffectionRule : Luban.BeanBase
{
    public EmotionAffectionRule() { }
    
    public EmotionAffectionRule(ByteBuf _buf) 
    {
        Emotion = _buf.ReadString();
        AffectionDelta = _buf.ReadInt();
    }

    public static EmotionAffectionRule DeserializeEmotionAffectionRule(ByteBuf _buf)
    {
        return new EmotionAffectionRule(_buf);
    }

    public string Emotion;
    public int AffectionDelta;

    public const int __ID__ = -2091268620;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref EmotionAffectionRule other)
    {
        if (other == null)
        {
            other = new EmotionAffectionRule();
        }
        other.Emotion = Emotion;
        other.AffectionDelta = AffectionDelta;
    }

    public EmotionAffectionRule DeepCopy()
    {
        var other = new EmotionAffectionRule();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "emotion:" + Emotion + ","
        + "affectionDelta:" + AffectionDelta + ","
        + "}";
    }
}
}

