
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class EmotionConfig : Luban.BeanBase
{
    public EmotionConfig() { }
    
    public EmotionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        EmotionName = _buf.ReadString();
        DisplayColor = _buf.ReadString();
    }

    public static EmotionConfig DeserializeEmotionConfig(ByteBuf _buf)
    {
        return new EmotionConfig(_buf);
    }

    /// <summary>
    /// 情绪ID
    /// </summary>
    public string Id;
    /// <summary>
    /// 情绪名
    /// </summary>
    public string EmotionName;
    /// <summary>
    /// 占位颜色 #RRGGBB
    /// </summary>
    public string DisplayColor;

    public const int __ID__ = -559231139;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref EmotionConfig other)
    {
        if (other == null)
        {
            other = new EmotionConfig();
        }
        other.Id = Id;
        other.EmotionName = EmotionName;
        other.DisplayColor = DisplayColor;
    }

    public EmotionConfig DeepCopy()
    {
        var other = new EmotionConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "emotionName:" + EmotionName + ","
        + "displayColor:" + DisplayColor + ","
        + "}";
    }
}
}

