
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class MemoryConfig : Luban.BeanBase
{
    public MemoryConfig() { }
    
    public MemoryConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        MemoryName = _buf.ReadString();
        Description = _buf.ReadString();
        {int n0 = _buf.ReadSize(); EmotionCardSet = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); EmotionCardSet.Add(_e0);}}
    }

    public static MemoryConfig DeserializeMemoryConfig(ByteBuf _buf)
    {
        return new MemoryConfig(_buf);
    }

    /// <summary>
    /// 记忆ID
    /// </summary>
    public string Id;
    /// <summary>
    /// 记忆名
    /// </summary>
    public string MemoryName;
    /// <summary>
    /// 描述
    /// </summary>
    public string Description;
    /// <summary>
    /// 关联情绪ID(逗号分隔)
    /// </summary>
    public System.Collections.Generic.List<string> EmotionCardSet;

    public const int __ID__ = 391576515;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref MemoryConfig other)
    {
        if (other == null)
        {
            other = new MemoryConfig();
        }
        other.Id = Id;
        other.MemoryName = MemoryName;
        other.Description = Description;
        other.EmotionCardSet = EmotionCardSet == null ? null : new System.Collections.Generic.List<string>(EmotionCardSet);
    }

    public MemoryConfig DeepCopy()
    {
        var other = new MemoryConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "memoryName:" + MemoryName + ","
        + "description:" + Description + ","
        + "emotionCardSet:" + Luban.StringUtil.CollectionToString(EmotionCardSet) + ","
        + "}";
    }
}
}

