
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class ReplyOptionConfig : Luban.BeanBase
{
    public ReplyOptionConfig() { }
    
    public ReplyOptionConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        ReplyText = _buf.ReadString();
        LockedText = _buf.ReadString();
        {int n0 = _buf.ReadSize(); RequiredMemory = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); RequiredMemory.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AllowedEmotion = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); AllowedEmotion.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RewardMemory = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); RewardMemory.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AffectionRules = new System.Collections.Generic.List<EmotionAffectionRule>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { EmotionAffectionRule _e0;  _e0 = global::GameProto.EmotionAffectionRule.DeserializeEmotionAffectionRule(_buf); AffectionRules.Add(_e0);}}
    }

    public static ReplyOptionConfig DeserializeReplyOptionConfig(ByteBuf _buf)
    {
        return new ReplyOptionConfig(_buf);
    }

    /// <summary>
    /// 回复ID
    /// </summary>
    public string Id;
    /// <summary>
    /// 正常回复
    /// </summary>
    public string ReplyText;
    /// <summary>
    /// 锁定文本
    /// </summary>
    public string LockedText;
    /// <summary>
    /// 需要记忆(逗号分隔)
    /// </summary>
    public System.Collections.Generic.List<string> RequiredMemory;
    /// <summary>
    /// 允许情绪(逗号分隔)
    /// </summary>
    public System.Collections.Generic.List<string> AllowedEmotion;
    /// <summary>
    /// 奖励记忆(逗号分隔)
    /// </summary>
    public System.Collections.Generic.List<string> RewardMemory;
    /// <summary>
    /// 情绪好感规则(元素;分隔,字段,分隔)
    /// </summary>
    public System.Collections.Generic.List<EmotionAffectionRule> AffectionRules;

    public const int __ID__ = 1843438593;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AffectionRules) { _e?.ResolveRef(tables); }
    }


    public void CopyTo(ref ReplyOptionConfig other)
    {
        if (other == null)
        {
            other = new ReplyOptionConfig();
        }
        other.Id = Id;
        other.ReplyText = ReplyText;
        other.LockedText = LockedText;
        other.RequiredMemory = RequiredMemory == null ? null : new System.Collections.Generic.List<string>(RequiredMemory);
        other.AllowedEmotion = AllowedEmotion == null ? null : new System.Collections.Generic.List<string>(AllowedEmotion);
        other.RewardMemory = RewardMemory == null ? null : new System.Collections.Generic.List<string>(RewardMemory);
        other.AffectionRules = AffectionRules == null ? null : new System.Collections.Generic.List<EmotionAffectionRule>(); if (AffectionRules != null) foreach (var _e in AffectionRules) { var _copy = _e; _e?.CopyTo(ref _copy); other.AffectionRules.Add(_copy); }
    }

    public ReplyOptionConfig DeepCopy()
    {
        var other = new ReplyOptionConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "replyText:" + ReplyText + ","
        + "lockedText:" + LockedText + ","
        + "requiredMemory:" + Luban.StringUtil.CollectionToString(RequiredMemory) + ","
        + "allowedEmotion:" + Luban.StringUtil.CollectionToString(AllowedEmotion) + ","
        + "rewardMemory:" + Luban.StringUtil.CollectionToString(RewardMemory) + ","
        + "affectionRules:" + Luban.StringUtil.CollectionToString(AffectionRules) + ","
        + "}";
    }
}
}

