
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public sealed partial class StoryNodeConfig : Luban.BeanBase
{
    public StoryNodeConfig() { }
    
    public StoryNodeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NpcId = _buf.ReadString();
        NpcText = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Replies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Replies.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Branches = new System.Collections.Generic.List<BranchRule>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { BranchRule _e0;  _e0 = global::GameProto.BranchRule.DeserializeBranchRule(_buf); Branches.Add(_e0);}}
        IsSessionEnd = _buf.ReadBool();
    }

    public static StoryNodeConfig DeserializeStoryNodeConfig(ByteBuf _buf)
    {
        return new StoryNodeConfig(_buf);
    }

    /// <summary>
    /// 节点ID
    /// </summary>
    public string Id;
    /// <summary>
    /// NPC ID
    /// </summary>
    public string NpcId;
    /// <summary>
    /// NPC文本
    /// </summary>
    public string NpcText;
    /// <summary>
    /// 回复选项ID(逗号分隔)
    /// </summary>
    public System.Collections.Generic.List<string> Replies;
    /// <summary>
    /// 分支规则
    /// </summary>
    public System.Collections.Generic.List<BranchRule> Branches;
    /// <summary>
    /// 是否会话结束
    /// </summary>
    public bool IsSessionEnd;

    public const int __ID__ = 1445114521;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Branches) { _e?.ResolveRef(tables); }
    }


    public void CopyTo(ref StoryNodeConfig other)
    {
        if (other == null)
        {
            other = new StoryNodeConfig();
        }
        other.Id = Id;
        other.NpcId = NpcId;
        other.NpcText = NpcText;
        other.Replies = Replies == null ? null : new System.Collections.Generic.List<string>(Replies);
        other.Branches = Branches == null ? null : new System.Collections.Generic.List<BranchRule>(); if (Branches != null) foreach (var _e in Branches) { var _copy = _e; _e?.CopyTo(ref _copy); other.Branches.Add(_copy); }
        other.IsSessionEnd = IsSessionEnd;
    }

    public StoryNodeConfig DeepCopy()
    {
        var other = new StoryNodeConfig();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "npcId:" + NpcId + ","
        + "npcText:" + NpcText + ","
        + "replies:" + Luban.StringUtil.CollectionToString(Replies) + ","
        + "branches:" + Luban.StringUtil.CollectionToString(Branches) + ","
        + "isSessionEnd:" + IsSessionEnd + ","
        + "}";
    }
}
}

