
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameProto
{
    public partial class Tables
    {
        #region The Tables

        private System.Func<string, ByteBuf> m_defaultLoader;

        /// <summary>
        /// 文本配置表
        /// </summary>
        private TbTextConfig m_TbTextConfig;
        public TbTextConfig TbTextConfig 
        {
            get
            {
                if (m_TbTextConfig == null)
                {
                    m_TbTextConfig = new TbTextConfig(m_defaultLoader("tbtextconfig"));
                    m_TbTextConfig.ResolveRef(this);
                }
                return m_TbTextConfig;
            }
            set
            {
                m_TbTextConfig = value;
                m_TbTextConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 道具配置表
        /// </summary>
        private TbItemConfig m_TbItemConfig;
        public TbItemConfig TbItemConfig 
        {
            get
            {
                if (m_TbItemConfig == null)
                {
                    m_TbItemConfig = new TbItemConfig(m_defaultLoader("tbitemconfig"));
                    m_TbItemConfig.ResolveRef(this);
                }
                return m_TbItemConfig;
            }
            set
            {
                m_TbItemConfig = value;
                m_TbItemConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 音效配置表
        /// </summary>
        private TbSoundConfig m_TbSoundConfig;
        public TbSoundConfig TbSoundConfig 
        {
            get
            {
                if (m_TbSoundConfig == null)
                {
                    m_TbSoundConfig = new TbSoundConfig(m_defaultLoader("tbsoundconfig"));
                    m_TbSoundConfig.ResolveRef(this);
                }
                return m_TbSoundConfig;
            }
            set
            {
                m_TbSoundConfig = value;
                m_TbSoundConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 音效随机配置表
        /// </summary>
        private TbSoundRandomConfig m_TbSoundRandomConfig;
        public TbSoundRandomConfig TbSoundRandomConfig 
        {
            get
            {
                if (m_TbSoundRandomConfig == null)
                {
                    m_TbSoundRandomConfig = new TbSoundRandomConfig(m_defaultLoader("tbsoundrandomconfig"));
                    m_TbSoundRandomConfig.ResolveRef(this);
                }
                return m_TbSoundRandomConfig;
            }
            set
            {
                m_TbSoundRandomConfig = value;
                m_TbSoundRandomConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 模型配置表
        /// </summary>
        private TbModelConfig m_TbModelConfig;
        public TbModelConfig TbModelConfig 
        {
            get
            {
                if (m_TbModelConfig == null)
                {
                    m_TbModelConfig = new TbModelConfig(m_defaultLoader("tbmodelconfig"));
                    m_TbModelConfig.ResolveRef(this);
                }
                return m_TbModelConfig;
            }
            set
            {
                m_TbModelConfig = value;
                m_TbModelConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 特效配置表
        /// </summary>
        private TbEffectConfig m_TbEffectConfig;
        public TbEffectConfig TbEffectConfig 
        {
            get
            {
                if (m_TbEffectConfig == null)
                {
                    m_TbEffectConfig = new TbEffectConfig(m_defaultLoader("tbeffectconfig"));
                    m_TbEffectConfig.ResolveRef(this);
                }
                return m_TbEffectConfig;
            }
            set
            {
                m_TbEffectConfig = value;
                m_TbEffectConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// GM配置表
        /// </summary>
        private TbGmConfig m_TbGmConfig;
        public TbGmConfig TbGmConfig 
        {
            get
            {
                if (m_TbGmConfig == null)
                {
                    m_TbGmConfig = new TbGmConfig(m_defaultLoader("tbgmconfig"));
                    m_TbGmConfig.ResolveRef(this);
                }
                return m_TbGmConfig;
            }
            set
            {
                m_TbGmConfig = value;
                m_TbGmConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 新手引导组配置表
        /// </summary>
        private TbGuideGroupConfig m_TbGuideGroupConfig;
        public TbGuideGroupConfig TbGuideGroupConfig 
        {
            get
            {
                if (m_TbGuideGroupConfig == null)
                {
                    m_TbGuideGroupConfig = new TbGuideGroupConfig(m_defaultLoader("tbguidegroupconfig"));
                    m_TbGuideGroupConfig.ResolveRef(this);
                }
                return m_TbGuideGroupConfig;
            }
            set
            {
                m_TbGuideGroupConfig = value;
                m_TbGuideGroupConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 新手引导步骤配置表
        /// </summary>
        private TbGuideStepConfig m_TbGuideStepConfig;
        public TbGuideStepConfig TbGuideStepConfig 
        {
            get
            {
                if (m_TbGuideStepConfig == null)
                {
                    m_TbGuideStepConfig = new TbGuideStepConfig(m_defaultLoader("tbguidestepconfig"));
                    m_TbGuideStepConfig.ResolveRef(this);
                }
                return m_TbGuideStepConfig;
            }
            set
            {
                m_TbGuideStepConfig = value;
                m_TbGuideStepConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 情绪配置表
        /// </summary>
        private TbEmotionConfig m_TbEmotionConfig;
        public TbEmotionConfig TbEmotionConfig 
        {
            get
            {
                if (m_TbEmotionConfig == null)
                {
                    m_TbEmotionConfig = new TbEmotionConfig(m_defaultLoader("tbemotionconfig"));
                    m_TbEmotionConfig.ResolveRef(this);
                }
                return m_TbEmotionConfig;
            }
            set
            {
                m_TbEmotionConfig = value;
                m_TbEmotionConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 记忆配置表
        /// </summary>
        private TbMemoryConfig m_TbMemoryConfig;
        public TbMemoryConfig TbMemoryConfig 
        {
            get
            {
                if (m_TbMemoryConfig == null)
                {
                    m_TbMemoryConfig = new TbMemoryConfig(m_defaultLoader("tbmemoryconfig"));
                    m_TbMemoryConfig.ResolveRef(this);
                }
                return m_TbMemoryConfig;
            }
            set
            {
                m_TbMemoryConfig = value;
                m_TbMemoryConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 回复选项配置表
        /// </summary>
        private TbReplyOptionConfig m_TbReplyOptionConfig;
        public TbReplyOptionConfig TbReplyOptionConfig 
        {
            get
            {
                if (m_TbReplyOptionConfig == null)
                {
                    m_TbReplyOptionConfig = new TbReplyOptionConfig(m_defaultLoader("tbreplyoptionconfig"));
                    m_TbReplyOptionConfig.ResolveRef(this);
                }
                return m_TbReplyOptionConfig;
            }
            set
            {
                m_TbReplyOptionConfig = value;
                m_TbReplyOptionConfig.ResolveRef(this);
            }
        }
        /// <summary>
        /// 剧情节点配置表
        /// </summary>
        private TbStoryNodeConfig m_TbStoryNodeConfig;
        public TbStoryNodeConfig TbStoryNodeConfig 
        {
            get
            {
                if (m_TbStoryNodeConfig == null)
                {
                    m_TbStoryNodeConfig = new TbStoryNodeConfig(m_defaultLoader("tbstorynodeconfig"));
                    m_TbStoryNodeConfig.ResolveRef(this);
                }
                return m_TbStoryNodeConfig;
            }
            set
            {
                m_TbStoryNodeConfig = value;
                m_TbStoryNodeConfig.ResolveRef(this);
            }
        }

        #endregion

        public Tables(System.Func<string, ByteBuf> loader)
        {
            SetDefaultLoader(loader);
            Init();
        }

        public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
        {
            m_defaultLoader = null;
            m_defaultLoader = loader;
        }

        public void Reload()
        {
            m_TbTextConfig = null;
            m_TbItemConfig = null;
            m_TbSoundConfig = null;
            m_TbSoundRandomConfig = null;
            m_TbModelConfig = null;
            m_TbEffectConfig = null;
            m_TbGmConfig = null;
            m_TbGuideGroupConfig = null;
            m_TbGuideStepConfig = null;
            m_TbEmotionConfig = null;
            m_TbMemoryConfig = null;
            m_TbReplyOptionConfig = null;
            m_TbStoryNodeConfig = null;
        }

        public void Init(){}
    }
}
