
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 情绪配置表
/// </summary>
public partial class TbEmotionConfig
{
    private readonly System.Collections.Generic.Dictionary<string, EmotionConfig> _dataMap;
    private readonly System.Collections.Generic.List<EmotionConfig> _dataList;
    
    public TbEmotionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, EmotionConfig>(n);
        _dataList = new System.Collections.Generic.List<EmotionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EmotionConfig _v;
            _v = global::GameProto.EmotionConfig.DeserializeEmotionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    #region 静态访问

    private static TbEmotionConfig m_instance;
    public static TbEmotionConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbEmotionConfig : m_instance;
    public static bool ContainsKey(string key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(string key, out EmotionConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static EmotionConfig GetOrDefault(string key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<string, EmotionConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<EmotionConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<string, EmotionConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<EmotionConfig> dataList => _dataList;

    public EmotionConfig GetOrDefaultNoStatic(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EmotionConfig Get(string key) => _dataMap[key];
    public EmotionConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

