
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 记忆配置表
/// </summary>
public partial class TbMemoryConfig
{
    private readonly System.Collections.Generic.Dictionary<string, MemoryConfig> _dataMap;
    private readonly System.Collections.Generic.List<MemoryConfig> _dataList;
    
    public TbMemoryConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, MemoryConfig>(n);
        _dataList = new System.Collections.Generic.List<MemoryConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            MemoryConfig _v;
            _v = global::GameProto.MemoryConfig.DeserializeMemoryConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    #region 静态访问

    private static TbMemoryConfig m_instance;
    public static TbMemoryConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbMemoryConfig : m_instance;
    public static bool ContainsKey(string key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(string key, out MemoryConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static MemoryConfig GetOrDefault(string key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<string, MemoryConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<MemoryConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<string, MemoryConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<MemoryConfig> dataList => _dataList;

    public MemoryConfig GetOrDefaultNoStatic(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public MemoryConfig Get(string key) => _dataMap[key];
    public MemoryConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

