
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 回复选项配置表
/// </summary>
public partial class TbReplyOptionConfig
{
    private readonly System.Collections.Generic.Dictionary<string, ReplyOptionConfig> _dataMap;
    private readonly System.Collections.Generic.List<ReplyOptionConfig> _dataList;
    
    public TbReplyOptionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, ReplyOptionConfig>(n);
        _dataList = new System.Collections.Generic.List<ReplyOptionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ReplyOptionConfig _v;
            _v = global::GameProto.ReplyOptionConfig.DeserializeReplyOptionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    #region 静态访问

    private static TbReplyOptionConfig m_instance;
    public static TbReplyOptionConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbReplyOptionConfig : m_instance;
    public static bool ContainsKey(string key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(string key, out ReplyOptionConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static ReplyOptionConfig GetOrDefault(string key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<string, ReplyOptionConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<ReplyOptionConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<string, ReplyOptionConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<ReplyOptionConfig> dataList => _dataList;

    public ReplyOptionConfig GetOrDefaultNoStatic(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ReplyOptionConfig Get(string key) => _dataMap[key];
    public ReplyOptionConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

