
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 音效随机配置表
/// </summary>
public partial class TbSoundRandomConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SoundRandomConfig> _dataMap;
    private readonly System.Collections.Generic.List<SoundRandomConfig> _dataList;
    
    public TbSoundRandomConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SoundRandomConfig>(n);
        _dataList = new System.Collections.Generic.List<SoundRandomConfig>(n);
        _groupedDataMap = new System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<SoundRandomConfig>>();
        for(int i = n ; i > 0 ; --i)
        {
            SoundRandomConfig _v;
            _v = global::GameProto.SoundRandomConfig.DeserializeSoundRandomConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
            int gid = _v.SoundID;
            if (!_groupedDataMap.TryGetValue(gid, out var list))
            {
                list = new System.Collections.Generic.List<SoundRandomConfig>();
                _groupedDataMap[gid] = list;
            }
            list.Add(_v);
        }
    }

    #region 静态访问

    private static TbSoundRandomConfig m_instance;
    public static TbSoundRandomConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbSoundRandomConfig : m_instance;
    public static bool ContainsKey(int key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(int key, out SoundRandomConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static SoundRandomConfig GetOrDefault(int key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<int, SoundRandomConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<SoundRandomConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<int, SoundRandomConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<SoundRandomConfig> dataList => _dataList;

    public SoundRandomConfig GetOrDefaultNoStatic(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SoundRandomConfig Get(int key) => _dataMap[key];
    public SoundRandomConfig this[int key] => _dataMap[key];

    #region GroupId 生成按组分配的字典数据

    public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<SoundRandomConfig>> _groupedDataMap;
    public static System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<SoundRandomConfig>> GroupedDataMap => Instance._groupedDataMap;

    public static System.Collections.Generic.List<SoundRandomConfig> GetListBySoundID(int groupID)
        => Instance._groupedDataMap.TryGetValue(groupID, out var list) ? list : null;

    #endregion
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

