
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
/// <summary>
/// 剧情节点配置表
/// </summary>
public partial class TbStoryNodeConfig
{
    private readonly System.Collections.Generic.Dictionary<string, StoryNodeConfig> _dataMap;
    private readonly System.Collections.Generic.List<StoryNodeConfig> _dataList;
    
    public TbStoryNodeConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, StoryNodeConfig>(n);
        _dataList = new System.Collections.Generic.List<StoryNodeConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            StoryNodeConfig _v;
            _v = global::GameProto.StoryNodeConfig.DeserializeStoryNodeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    #region 静态访问

    private static TbStoryNodeConfig m_instance;
    public static TbStoryNodeConfig Instance => m_instance == null ? m_instance = ConfigSystem.Instance.Tables.TbStoryNodeConfig : m_instance;
    public static bool ContainsKey(string key) => Instance._dataMap.ContainsKey(key);
    public static bool TryGetValue(string key, out StoryNodeConfig v) => Instance._dataMap.TryGetValue(key, out v);
    public static StoryNodeConfig GetOrDefault(string key) => Instance._dataMap.TryGetValue(key, out var v) ? v : null;
    public static System.Collections.Generic.Dictionary<string, StoryNodeConfig> DataMap => Instance._dataMap;
    public static System.Collections.Generic.List<StoryNodeConfig> DataList => Instance._dataList;

    #endregion

    public System.Collections.Generic.Dictionary<string, StoryNodeConfig> dataMap => _dataMap;
    public System.Collections.Generic.List<StoryNodeConfig> dataList => _dataList;

    public StoryNodeConfig GetOrDefaultNoStatic(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StoryNodeConfig Get(string key) => _dataMap[key];
    public StoryNodeConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

