
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameProto
{
public partial struct vector3
{
    
    public vector3(ByteBuf _buf) 
    {
        X = _buf.ReadFloat();
        Y = _buf.ReadFloat();
        Z = _buf.ReadFloat();
    }

    public static vector3 Deserializevector3(ByteBuf _buf)
    {
        return new vector3(_buf);
    }

    public float X;
    public float Y;
    public float Z;


    public  void ResolveRef(Tables tables)
    {
    }


    public void CopyTo(ref vector3 other)
    {
        other.X = X;
        other.Y = Y;
        other.Z = Z;
    }

    public vector3 DeepCopy()
    {
        var other = new vector3();
        CopyTo(ref other);
        return other;
    }
    
    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}
}

